### ISSUE TITLE
关于scheme

### ISSUE THREAD

**Issue by caopoy** [bolnh/hexo-theme-material#746]
图片上看似乎有三个scheme，可是config里面只看到两个scheme

而且使用Isolation scheme时，似乎无法显示文章，只显示侧边栏

**Comment by SkyYkb** [comment]
Same problem.

**Comment by HTensor** [comment]
Same problem.

**Comment by HTensor** [comment]
```
# JS Effect Switches
js_effect:
    fade: false
    smoothscroll: false
```

修改 fade 为 false 即可解决
