### ISSUE TITLE
配置评论系统之后生成错误

### ISSUE THREAD

**Issue by ZONGQUAN-HU** [bolnh/hexo-theme-material#776]
**I certify that I have first consulted** (check all with "x")

**我确认我已经查看了** (使用 "x" 选择)

- [x ] [Hexo documentation | Hexo 文档](https://hexo.io/docs/)
- [ x] [Material theme documentation | Material 主题文档](https://material.viosey.com/)
- [x ] [Material theme issues | Material 主题的其它 issue](https://github.com/viosey/hexo-theme-material/issues?utf8=%E2%9C%93&q=is%3Aissue)

----

**I'm submitting a**  (check one with "x")

**我正在申请**  (使用 "x" 选择)

- [x] bug report | 反馈一个 bug
- [ ] feature request | 申请添加新的特性或功能
- [ x] support request | 请求技术支持

错误内容
```bash
ubuntu@ubuntu:~/myblog$ hexo g -d
INFO  Validating config
INFO  Start processing
ERROR Theme config load failed.
ERROR {
  err: YAMLException: can not read a block mapping entry; a multiline key may not be an implicit key (244:20)
  
   241 |     changyan_appid:cy******
   242 |     changyan_conf:prod_******f60f ...
   243 |     changyan_thread_key_type:path
   244 |     livere_data_uid: 
  --------------------------^
   245 |     gitment_repo:   # git repo of the hexo
   246 |     gitment_owner:  # git repo's owner
      at generateError (/home/ubuntu/myblog/node_modules/js-yaml/lib/loader.js:183:10)
      at throwError (/home/ubuntu/myblog/node_modules/js-yaml/lib/loader.js:187:9)
      at readBlockMapping (/home/ubuntu/myblog/node_modules/js-yaml/lib/loader.js:1145:9)
      at composeNode (/home/ubuntu/myblog/node_modules/js-yaml/lib/loader.js:1441:12)
      at readBlockMapping (/home/ubuntu/myblog/node_modules/js-yaml/lib/loader.js:1164:11)
      at composeNode (/home/ubuntu/myblog/node_modules/js-yaml/lib/loader.js:1441:12)
      at readDocument (/home/ubuntu/myblog/node_modules/js-yaml/lib/loader.js:1625:3)
```
配置文件中评论系统部分的内容
```yaml
# Comment Systems
# Available value of "use":
#     disqus | disqus_click | changyan | livere | gitment | gitalk | valine | wildfire
# If you want to use gitment or gitalk,you should get the client_id and client_secret from https://github.com/settings/applications/new
# If you want to use valine,you should get the app_id and app_key from https://leancloud.cn ,more setting please see https://valine.js.org
comment:
    use: changyan
#    shortname:  duoshuo or disqus shortname
    changyan_appid:c****R
    changyan_conf:prod_****9
    changyan_thread_key_type:path
    livere_data_uid:
    gitment_repo:   # git repo of the hexo
    gitment_owner:  # git repo's owner
    gitment_client_id:  # github app client id
    gitment_client_secret :  # github app client secret
    valine_leancloud_appId:  # leancloud application app id
    valine_leancloud_appKey:  # leancloud application app key
    valine_notify: false # valine mail notify (true/false) https://github.com/xCss/Valine/wiki
    valine_verify: false # valine verify code (true/false)
    valine_pageSize: 10 # comment list page size
    valine_avatar: identicon # gravatar style https://valine.js.org/#/avatar
    valine_lang: zh-cn # i18n
    valine_placeholder: Just go go # valine comment input placeholder(like: Please leave your footprints )
    valine_guest_info: nick,mail,link #valine comment header info
    gitalk_repo: # git repo of the hexo
    gitalk_owner: # git repo's owner
    gitalk_client_id: # github app client id
    gitalk_client_secret: # github app client secret
    wildfire_database_provider: firebase # firebase or wilddog
    wildfire_wilddog_site_id:
    wildfire_firebase_api_key:
    wildfire_firebase_auth_domain:
    wildfire_firebase_database_url:
    wildfire_firebase_project_id:
    wildfire_firebase_storage_bucket:
    wildfire_firebase_messaging_sender_id:
    wildfire_theme: light # light or dark
    wildfire_locale: en # en or zh-CN

```
这是空白键有关系吗，到底想要怎么填？
